<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <legacyMode>false</legacyMode>
            <updateRate>100</updateRate>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <torque>1000</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom_raw</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometrySource>1</odometrySource>
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <publishWheelTF>false</publishWheelTF>
            <!-- publishOdomTF false if using sensor fusion (robot_localization), otherwise true -->
            <publishOdomTF>false</publishOdomTF>
            <publishTf>1</publishTf>
            <wheelTorque>5</wheelTorque>
            <publishWheelJointState>true</publishWheelJointState>
            <wheelAcceleration>0</wheelAcceleration>
            <rosDebugLevel>na</rosDebugLevel>
        </plugin>
    </gazebo>

</robot>