<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="${lidar_x_offset} 0 ${lidar_z_offset - 0.0171}" rpy="0 0 ${pi}"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <origin rpy="0 0 ${pi}" xyz="0 0 0.0171"/>
            <geometry>
                <mesh filename="package://astro/meshes/ASTRO_LidarAssembly.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="dark_gray"/>
        </visual>
        <collision>
            <origin rpy="0 0 ${pi}" xyz="0 0 0.0171"/>
            <geometry>
                <mesh filename="package://astro/meshes/ASTRO_LidarAssembly.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="laser_frame">
        <material>Gazebo/DarkGrey</material>
        <sensor type="ray" name="laser">
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>360</samples>
                    <resolution>1</resolution>
                    <min_angle>-3.141592 </min_angle>
                    <max_angle>3.141592 </max_angle>
                </horizontal>
                </scan>
                <range>
                <min>0.3</min>
                <max>12.0</max>
                <resolution>0.01</resolution>
                </range>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.005</stddev>
                </noise>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser_frame</frameName>
            </plugin>
        </sensor>
    </gazebo>
</robot>