<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Properties definitions -->
    <xacro:property name="wheel_radius" value="0.0360"/>
    <xacro:property name="wheel_thickness" value="0.0320"/>
    <xacro:property name="wheel_mass" value="0.085"/>
    <!-- <xacro:property name="wheel_separation" value="0.2932"/> -->
    <xacro:property name="wheel_separation" value="0.287"/> 
    <xacro:property name="chassis_base_to_lidar_height" value="0.0881"/>
    <xacro:property name="lidar_x_offset" value="0.036857"/>
    <xacro:property name="ground_clearance" value="0.0146"/>
    <xacro:property name="base_thickness" value="0.01"/>
    <xacro:property name="chassis_mass" value="3.0"/>
    <xacro:property name="caster_wheel_mass" value="0.02"/>
    <xacro:property name="chassis_length" value="0.32"/>
    <xacro:property name="chassis_width" value="0.337"/>
    <xacro:property name="chassis_height" value="0.085"/>
    <xacro:property name="chassis_inertial_offset_x" value="0.015"/>
    <xacro:property name="realsense_x_offset" value="0.175"/>
    <xacro:property name="realsense_z_offset_chassis" value="0.0425"/>
    <xacro:property name="realsense_depth_offset" value="0.0175"/>
    <xacro:property name="realsense_depth_to_infra1_offset" value="0.0"/>
    <xacro:property name="realsense_depth_to_infra2_offset" value="-0.050"/>
    <xacro:property name="realsense_depth_to_color_offset" value="0.015"/>
    <xacro:property name="imu_x_offset_chassis" value="-0.03"/>
    <xacro:property name="imu_z_offset_chassis" value="0.0881"/>
    <xacro:property name="friction_mu" value="5.0"/>

    <!-- Imports -->
    <xacro:include filename="inertial_macros.xacro"/> 
    <xacro:include filename="materials.xacro"/>
    <xacro:include filename="caster_wheels.xacro"/>

    <!-- Base Footprint and Base Link -->
    <link name="base_footprint"/>

    <joint name="base_link_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link ="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="base_link" />

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link ="chassis"/>
        <origin xyz="0 0 ${ground_clearance-wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://astro/description/meshes/Chassis.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://astro/description/meshes/Chassis.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_inertial_offset_x} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Left Wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_separation/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Orange</material>
        <mu1 value="${friction_mu}"/>
        <mu2 value="${friction_mu}"/>
    </gazebo>

    <!-- Right Wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Orange</material>
        <mu1 value="${friction_mu}"/>
        <mu2 value="${friction_mu}"/>
    </gazebo>

</robot>