obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.2

#footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.240

inflation_radius: 0.5
cost_scaling_factor: 5.0

lethal_cost_threshold: 100.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}