controller_manager:
  ros_parameters:
    update_rate: 100

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController
    
    js_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
diffdrive_controller:
  publish_rate: 100.0

  base_frame_id: base_link

  left_wheel_names: ['left_wheel_joint']
  right_wheel_names: ['right_wheel_joint']
  wheel_separation: 0.306
  wheel_radius: 0.036

  use_stamped_vel: false
