controller_manager:
  ros_parameters:
    update_rate: 100

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController
    
    js_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
diffdrive_controller:
  publish_rate: 100.0

  base_frame_id: base_footprint

  left_wheel_names: ['left_wheel_joint']
  right_wheel_names: ['right_wheel_joint']
  wheel_separation: 0.306
  wheel_radius: 0.036
  wheels_per_side: 1
  
  use_stamped_vel: false
  enable_odom_tf: false
  position_feedback: true

  linear.x.has_velocity_limits: true
  linear.x.has_acceleration_limits: false
  linear.x.has_jerk_limits: false
  linear.x.max_velocity: 0.75
  linear.x.min_velocity: 0.0
  linear.x.max_acceleration: 0.0
  linear.x.min_acceleration: 0.0
  linear.x.max_jerk: 0.0
  linear.x.min_jerk: 0.0

  angular.z.has_velocity_limits: true
  angular.z.has_acceleration_limits: false
  angular.z.has_jerk_limits: false
  angular.z.max_velocity: 4.9
  angular.z.min_velocity: 0.0
  angular.z.max_acceleration: 0.0
  angular.z.min_acceleration: 0.0
  angular.z.max_jerk: 0.0
  angular.z.min_jerk: 0.0
  
