frequency: 30
two_d_mode: true
publish_tf: true
 
# Coordinate frame specification
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
#map_frame: map
 
# The odom0 configuration
odom0: /odom_raw
odom0_config: [true, true, false,
               false, false, true,
               true,  true,  false,
               false, false, true,
               false, false, false,]
odom0_differential: false
 
# The imu0 configuration
imu0: /imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true,  false, false,]
imu0_differential: false